import json,re,hashlib,pymupdf,difflib
from pathlib import Path
base=Path('data/small_track_real_training');p=Path('data/small_track_legacy/official-history-informator-2025.pdf');d=pymupdf.open(p)
def clean(i):return '\n'.join(x for x in d[i].get_text(sort=True).splitlines() if not re.search(r'Informator o egzaminie|Przykładowe zadania z rozwiązaniami',x)).strip()
rows=[json.loads((base/'supplemental-official-essay.jsonl').read_text())]
evaltexts=[json.loads(x)['question'] for y in [2023,2024] for x in Path(f'data/small_track/{y}-05/candidate.jsonl').read_text().splitlines() if json.loads(x)['subtype']=='essay']
for n,qpage,start,end,grade in [(1,81,82,84,12),(3,92,93,94,15),(4,97,98,99,12)]:
 q=re.split(r'Przykład\s+\d+\.?',clean(qpage-1),maxsplit=1)[1].split('Wymagania ogólne')[0].strip()
 t='\n'.join(clean(i-1) for i in range(start,end+1));a=re.split(r'Realizacja 1\.?',t,maxsplit=1)[1].split('A. Narracja historyczna:')[0];a=re.sub(r'ok\.\s*\d+\s+słów\s*$','',a).strip()
 assert len(a.split())>300 and not any(q==e for e in evaltexts)
 rows.append({'id':f'cke-informator2025-essay-{n}','paper_id':'cke-informator2025','year':2025,'publication_year':2024,'source_kind':'official guide exemplar, not2024 evaluation paper','category':'essay','synthetic':False,'source_url':'https://bip.cke.gov.pl/attachments/download/10016','source_pdf_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source_pages':[qpage,*range(start,end+1)],'official_awarded_points':grade,'official_max_points':15,'images_encoded_by_model':False,'evaluation_overlap_check':'Prompt text differs from both2023/24 full official essay tasks; guide is separate publication','messages':[{'role':'system','content':'Rozwiąż zadanie maturalne z historii. Odpowiedz po polsku, konkretnie i zgodnie z poleceniem.'},{'role':'user','content':q},{'role':'assistant','content':a}]})
(base/'essay/train.jsonl').write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in rows));m=json.loads((base/'manifest.json').read_text());m['files']['essay']={'rows':len(rows),'sha256':hashlib.sha256((base/'essay/train.jsonl').read_bytes()).hexdigest()};m['official_essay_supplement']={'rows':4,'source_urls':['https://bip.cke.gov.pl/attachments/download/8286','https://bip.cke.gov.pl/attachments/download/10016'],'status':'Four actual official exemplars; Charlemagne excluded for2024evaluationtopic overlap. No synthesis.'};(base/'manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print([(r['id'],len(r['messages'][-1]['content'].split()),r['official_awarded_points']) for r in rows]);print('manifest',hashlib.sha256((base/'manifest.json').read_bytes()).hexdigest())
