#!/bin/bash
# Essay arms (harness thread, 22:48 CEST) on the 12 dev essays, gemma4-12b-think8k (16k essay budget), own :8101 server (4 slots x 40k) beside main_v9 on :8100 (best-score thread 23:37 CEST).
L=/scratch/master_chain.log; log() { echo "$(date -u +%H:%M:%S) V9 $*" >> $L; }
export THINK_FALLBACK=1; cd /scratch/repo4
C="python scripts/subtype_sweep.py --base-url http://127.0.0.1:8101/v1 --papers dev --only-papers none --all-essays --model gemma4-12b-think8k --concurrency 4"
s=$(date +%s); $C --subtypes essay --candidates base,plan,guard,plan_guard --out results/subtype/essay-grid > /scratch/out/essay-grid.console 2>&1; log "END essay-grid rc=$? wall $(( $(date +%s)-s ))s"
s=$(date +%s); ESSAY_TARGET_WORDS=550 ESSAY_MIN_WORDS=350 $C --candidates none --raw --out results/subtype/essay-len > /scratch/out/essay-len.console 2>&1; log "END essay-len rc=$? wall $(( $(date +%s)-s ))s"
s=$(date +%s); ESSAY_BEST_OF=3 ESSAY_TARGET_WORDS=550 ESSAY_MIN_WORDS=350 $C --subtypes essay --candidates plan --raw --out results/subtype/essay-bo3 > /scratch/out/essay-bo3.console 2>&1; log "END essay-bo3 rc=$? wall $(( $(date +%s)-s ))s"
# E4 (raw think8k on the practice papers) is covered by sweep arms tb8k + te16k.
# E5 rag_plan at 16k, E6 plan + best-of-3 without the length guard (harness thread 00:15 CEST)
s=$(date +%s); RAG_PATH=data/kb/factsheets.jsonl,data/kb/passages.jsonl $C --subtypes essay --candidates rag_plan --out results/subtype/essay-ragplan > /scratch/out/essay-ragplan.console 2>&1; log "END essay-ragplan rc=$? wall $(( $(date +%s)-s ))s"
s=$(date +%s); ESSAY_BEST_OF=3 ESSAY_MIN_WORDS=0 $C --subtypes essay --candidates plan --out results/subtype/essay-bo3plan > /scratch/out/essay-bo3plan.console 2>&1; log "END essay-bo3plan rc=$? wall $(( $(date +%s)-s ))s"
# H1/H2 held-out essay confirmation (harness thread 01:16 CEST), ahead of E7
s=$(date +%s); for r in 1 2; do THINK_FALLBACK=1 python scripts/subtype_sweep.py --base-url http://127.0.0.1:8101/v1 --papers heldout --only-papers none --all-essays --subtypes essay --candidates none --raw --model gemma4-12b-think --concurrency 8 --out results/subtype/heldout-essay/base-r$r > /scratch/out/heldout-essay-base-r$r.console 2>&1; done; log "END heldout-essay H1 base rc=$? wall $(( $(date +%s)-s ))s"
s=$(date +%s); for r in 1 2; do ESSAY_BEST_OF=3 ESSAY_MIN_WORDS=0 THINK_FALLBACK=1 python scripts/subtype_sweep.py --base-url http://127.0.0.1:8101/v1 --papers heldout --only-papers none --all-essays --subtypes essay --candidates plan --model gemma4-12b-think --concurrency 8 --out results/subtype/heldout-essay/bo3plan-r$r > /scratch/out/heldout-essay-bo3plan-r$r.console 2>&1; done; log "END heldout-essay H2 bo3plan rc=$? wall $(( $(date +%s)-s ))s"
for r in 1 2; do rm -rf results/subtype/heldout-essay/bo3plan-noguard-r$r; mv results/subtype/heldout-essay/bo3plan-r$r results/subtype/heldout-essay/bo3plan-noguard-r$r; done
s=$(date +%s); for r in 1 2; do ESSAY_BEST_OF=3 ESSAY_MIN_WORDS=350 ESSAY_TARGET_WORDS=550 THINK_FALLBACK=1 python scripts/subtype_sweep.py --base-url http://127.0.0.1:8101/v1 --papers heldout --only-papers none --all-essays --subtypes essay --candidates plan --model gemma4-12b-think --concurrency 8 --out results/subtype/heldout-essay/bo3plan-r$r > /scratch/out/heldout-essay-bo3plan-guard-r$r.console 2>&1; done; log "END heldout-essay H2 bo3plan-guard rc=$? wall $(( $(date +%s)-s ))s"
s=$(date +%s); for r in 1 2; do RAG_PATH=data/kb/factsheets.jsonl,data/kb/passages.jsonl THINK_FALLBACK=1 python scripts/subtype_sweep.py --base-url http://127.0.0.1:8101/v1 --papers heldout --only-papers none --all-essays --subtypes essay --candidates rag_plan --model gemma4-12b-think --concurrency 8 --out results/subtype/heldout-essay/ragplan-r$r > /scratch/out/heldout-essay-ragplan-r$r.console 2>&1; done; log "END heldout-essay H3 ragplan rc=$? wall $(( $(date +%s)-s ))s"
# E8 rag_bo3plan on the dev essays (harness thread 01:42 CEST), after H1-H3, before E7
s=$(date +%s); RAG_PATH=data/kb/passages.jsonl,data/kb/factsheets.jsonl ESSAY_BEST_OF=3 ESSAY_MIN_WORDS=350 ESSAY_TARGET_WORDS=550 THINK_FALLBACK=1 python scripts/subtype_sweep.py --base-url http://127.0.0.1:8101/v1 --papers dev --only-papers none --all-essays --subtypes essay --candidates rag_plan --model gemma4-12b-think8k --concurrency 8 --out results/subtype/essay-ragbo3plan > /scratch/out/essay-ragbo3plan.console 2>&1; log "END essay-ragbo3plan rc=$? wall $(( $(date +%s)-s ))s"
# E7 deferred: the stage rehearsal needs this VRAM (02:59 CEST)
