#!/usr/bin/env python3
"""Running table of every Claude-graded run on the held-out papers -> results/judged/TABLE.md.

    python scripts/judge_table.py        # rewrite results/judged/TABLE.md from results/judged/*/<paper>/claude_score.json

Rows = runs; columns = the four papers (/60), total, total without 2023-05 item 16.2 (a training row shared its fact;
"Win best matura score" reports both), essay subtotal, and Sol's total where a sol_score.json exists.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
J = ROOT / "results/judged"
PAPERS = ["2023-05", "2024-05", "2025-05", "2026-05"]
EXCLUDE = ("2023-05", "16.2")
ESSAY = {"2023-05": "26", "2024-05": "26", "2025-05": "25", "2026-05": "26"}


def main():
    rows = []
    for run in sorted(p for p in J.iterdir() if p.is_dir()):
        cells, tot, mx, ess, emx, sol, solp, model, ex = {}, 0, 0, 0, 0, 0, 0, "", 0
        for p in PAPERS:
            f = run / p / "claude_score.json"
            if not f.exists():
                continue
            d = json.loads(f.read_text())
            model = model or d.get("model", "")
            cells[p] = d["total"]
            tot += d["total"]
            mx += d["max"]
            for it in d["items"]:
                if (p, it["id"]) == EXCLUDE:
                    ex = it["claude_points"]
                if it["id"] == ESSAY[p]:
                    ess += it["claude_points"]
                    emx += it["max_points"]
            s = run / p / "sol_score.json"
            if s.exists():
                sol += json.loads(s.read_text())["total"]
                solp += 1
        if not cells:
            continue
        rows.append((ex, run.name, model, cells, tot, mx, ess, emx, sol if solp else None, solp))
    rows.sort(key=lambda r: -r[4])
    out = ["# Claude judge vs CKE klucz: held-out May 2023-2026 (auto-generated by scripts/judge_table.py)", "",
           "| Run | Model | 2023 | 2024 | 2025 | 2026 | Total | Total w/o 2023 z16.2 | Essay | Sol |",
           "|---|---|---|---|---|---|---|---|---|---|"]
    for ex, name, model, cells, tot, mx, ess, emx, sol, solp in rows:
        pc = [f"{cells[p]:g}" if p in cells else "-" for p in PAPERS]
        s = "-" if sol is None else f"{sol:g}" + ("" if solp == len(cells) else f" ({solp} papers)")
        out.append(f"| {name} | {model} | " + " | ".join(pc) + f" | **{tot:g}/{mx:g}** | {tot - ex:g}/{mx - (1 if '2023-05' in cells else 0):g} | {ess:g}/{emx:g} | {s} |")
    (J / "TABLE.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
